#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DEFAULT VALUES FOR CONFIGURATION
#=================================================

xms=256m
xmx=1g

ynh_app_setting_set --app=$app --key=xms --value=$xms
ynh_app_setting_set --app=$app --key=xmx --value=$xmx

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=15

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" 

chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"

#=================================================
# ADD CONFIGURATIONS
#=================================================
ynh_script_progression --message="Adding the configuration files..." --weight=1

ynh_add_config --template="elasticsearch.yml" --destination="$install_dir/config/elasticsearch.yml"
ynh_add_config --template="jvm.options" --destination="$install_dir/config/jvm.options.d/yunohost.options"

chmod 400 "$install_dir/config/elasticsearch.yml" "$install_dir/config/jvm.options.d/yunohost.options"
chown $app:$app "$install_dir/config/elasticsearch.yml" "$install_dir/config/jvm.options.d/yunohost.options"

#=================================================
# INCREASE MAX_MAP_COUNT
#=================================================
ynh_script_progression --message="Increasing maximum map count (sysctl)..."

# Increase the maximum number of files inotify can monitor.
cp -a ../conf/90-max_map_count-elasticsearch.conf /etc/sysctl.d/
# Then, reload the kernel configuration.
if ! [ "${container:-}" = "lxc" ] # lxc doesn't allow sysctl to play with kernel options.
then
	sysctl -p /etc/sysctl.d/90-max_map_count-elasticsearch.conf
fi

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..." --weight=1

# Create a dedicated systemd config
ynh_add_systemd_config

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

yunohost service add $app --description="Distributed and RESTful search engine" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
