#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service integration..." --weight=1
	yunohost service remove $app
fi

# Remove the dedicated systemd config
ynh_remove_systemd_config

# Remove the app-specific logrotate config
ynh_remove_logrotate

if [ -e "/etc/sysctl.d/90-max_map_count-elasticsearch.conf" ]; then
	ynh_secure_remove --file="/etc/sysctl.d/90-max_map_count-elasticsearch.conf"
	# Reload the kernel configuration.
	if ! [ "${container:-}" = "lxc" ] # lxc doesn't allow sysctl to play with kernel options.
	then
		sysctl --system
	fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
